#include "povexport/pov_writer.hpp"

#include <algorithm>
#include <cmath>
#include <cstdint>
#include <fstream>
#include <map>
#include <stdexcept>
#include <vector>

namespace umbreon {
namespace {

// Quantized RGBA key used to deduplicate per-corner colors into a palette.
std::uint32_t colorKey(const Vec4& c) {
  auto q = [](float v) {
    float x = std::min(1.0f, std::max(0.0f, v));
    return static_cast<std::uint32_t>(x * 255.0f + 0.5f);
  };
  return (q(c.x) << 24) | (q(c.y) << 16) | (q(c.z) << 8) | q(c.w);
}

void writeVec(std::ofstream& f, const Vec3& v) {
  f << '<' << v.x << ',' << v.y << ',' << v.z << '>';
}

}  // namespace

void writePovScene(const std::string& path, const Scene& scene,
                   const PovWriteOptions& opt) {
  const Mesh& m = scene.mesh;
  std::ofstream f(path);
  if (!f) throw std::runtime_error("cannot open POV output: " + path);
  f.precision(7);

  // --- combined world bounds ---
  Aabb base = m.bounds();
  Aabb world;
  if (scene.instanceOffsets.empty()) {
    world = base;
  } else {
    for (const Vec3& o : scene.instanceOffsets) {
      world.extend(base.lo + o);
      world.extend(base.hi + o);
    }
  }
  Vec3 center = world.center();
  float wdiag = world.diagonal();

  // --- header + radiosity ---
  f << "// POV-Ray scene generated by umbreon for benchmarking.\n";
  f << "#version 3.7;\n";
  if (opt.radiosity) f << "#include \"rad_def.inc\"\n";
  f << "global_settings {\n  assumed_gamma 1.0\n";
  if (opt.radiosity)
    f << "  radiosity { Rad_Settings(" << opt.radiosityQuality
      << ", off, off) }\n";
  f << "}\n\n";

  f << "background { color rgb <" << scene.background.x << ','
    << scene.background.y << ',' << scene.background.z << "> }\n\n";

  // --- camera: explicit vectors matching the umbreon camera basis ---
  Vec3 d = normalize(scene.camera.direction);
  Vec3 r = normalize(cross(d, scene.camera.up));
  Vec3 u = normalize(cross(r, d));
  float aspect = static_cast<float>(opt.width) / static_cast<float>(opt.height);
  float th = std::tan(radians(scene.camera.fovy * 0.5f));
  Vec3 rightV = r * (2.0f * th * aspect);
  Vec3 upV = u * (2.0f * th);
  f << "camera {\n  location ";
  writeVec(f, scene.camera.position);
  f << "\n  direction ";
  writeVec(f, d);
  f << "\n  right ";
  writeVec(f, rightV);
  f << "\n  up ";
  writeVec(f, upV);
  f << "\n}\n\n";

  // --- emissive environment sphere (radiosity ambient source) ---
  // no_image keeps it out of the camera image (so the dark background shows)
  // while it still emits light gathered by radiosity.
  if (opt.radiosity) {
    float envR = wdiag * 4.0f + 1.0f;
    f << "sphere {\n  ";
    writeVec(f, center);
    f << ", " << envR << "\n";
    f << "  texture { pigment { color rgb 1 } "
         "finish { diffuse 0 emission 0.5 } }\n";
    f << "  hollow on\n  no_shadow\n  no_image\n}\n\n";
  }

  // --- key light(s) ---
  // POV light_source brightness is tuned independently of the umbreon light
  // intensity (the two renderers' light units are not comparable).
  for (const DistantLight& L : scene.lights) {
    Vec3 lp = center - normalize(L.direction) * (wdiag * 3.0f + 1.0f);
    Vec3 c = L.color * 0.85f;
    f << "light_source {\n  ";
    writeVec(f, lp);
    f << "\n  color rgb <" << c.x << ',' << c.y << ',' << c.z << ">\n";
    f << "  parallel\n  point_at ";
    writeVec(f, center);
    f << "\n}\n\n";
  }

  // --- deduplicate per-vertex colors into a palette ---
  std::vector<Vec4> palette;
  std::map<std::uint32_t, int> colorIndex;
  std::vector<int> vertTex(m.colors.size());  // vertex -> palette index
  for (std::size_t i = 0; i < m.colors.size(); ++i) {
    std::uint32_t k = colorKey(m.colors[i]);
    auto it = colorIndex.find(k);
    if (it == colorIndex.end()) {
      int idx = static_cast<int>(palette.size());
      colorIndex[k] = idx;
      palette.push_back(m.colors[i]);
      vertTex[i] = idx;
    } else {
      vertTex[i] = it->second;
    }
  }

  // Under radiosity the bounced light supplies the ambient term, so the
  // material's own ambient is kept low; otherwise use the POV finish ambient.
  float povAmbient = opt.radiosity ? 0.05f : m.material.ambient;
  float rough = std::max(1.0e-3f, m.material.roughness);

  // --- mesh2 declaration ---
  f << "#declare PocMesh = mesh2 {\n";

  f << "  vertex_vectors {\n    " << m.positions.size() << ",\n    ";
  for (std::size_t i = 0; i < m.positions.size(); ++i) {
    writeVec(f, m.positions[i]);
    if (i + 1 < m.positions.size()) f << ',';
    if (i % 4 == 3) f << "\n    ";
  }
  f << "\n  }\n";

  f << "  normal_vectors {\n    " << m.normals.size() << ",\n    ";
  for (std::size_t i = 0; i < m.normals.size(); ++i) {
    writeVec(f, m.normals[i]);
    if (i + 1 < m.normals.size()) f << ',';
    if (i % 4 == 3) f << "\n    ";
  }
  f << "\n  }\n";

  f << "  texture_list {\n    " << palette.size() << ",\n";
  for (std::size_t i = 0; i < palette.size(); ++i) {
    const Vec4& c = palette[i];
    f << "    texture { pigment { color rgb <" << c.x << ',' << c.y << ','
      << c.z << "> } finish { ambient " << povAmbient << " diffuse "
      << m.material.diffuse << " specular " << m.material.specular
      << " roughness " << rough << " } }";
    if (i + 1 < palette.size()) f << ',';
    f << '\n';
  }
  f << "  }\n";

  f << "  face_indices {\n    " << m.triangleCount() << ",\n    ";
  for (std::size_t t = 0; t < m.triangleCount(); ++t) {
    const int va = static_cast<int>(m.cornerVertex(3 * t));
    const int vb = static_cast<int>(m.cornerVertex(3 * t + 1));
    const int vc = static_cast<int>(m.cornerVertex(3 * t + 2));
    const int ta = vertTex[va], tb = vertTex[vb], tc = vertTex[vc];
    f << '<' << va << ',' << vb << ',' << vc << ">,";
    if (ta == tb && tb == tc) {
      f << ta;
    } else {
      f << ta << ',' << tb << ',' << tc;
    }
    if (t + 1 < m.triangleCount()) f << ',';
    if (t % 4 == 3) f << "\n    ";
  }
  f << "\n  }\n}\n\n";

  // --- one object per grid instance ---
  if (scene.instanceOffsets.empty()) {
    f << "object { PocMesh }\n";
  } else {
    for (const Vec3& o : scene.instanceOffsets) {
      f << "object { PocMesh translate ";
      writeVec(f, o);
      f << " }\n";
    }
  }
}

}  // namespace umbreon
